### ISSUE TITLE
Error when deploying SDXL on SageMaker with optimum neuron and hf neuronx inference container

### ISSUE THREAD

**Issue by pinak-p** [philschmid/huggingface-inferentia2-samples#16]
Updated this [example](https://github.com/philschmid/huggingface-inferentia2-samples/blob/main/stable-diffusion-xl/sagemaker-notebook.ipynb) to use optimum-neuron 0.0.25 and the latest [Huggingface Neuronx container for SageMaker](763104351884.dkr.ecr.us-east-2.amazonaws.com/huggingface-pytorch-inference-neuronx:2.1.2-transformers4.43.2-neuronx-py310-sdk2.20.0-ubuntu20.04)

Model compiled with:
```
optimum-cli export neuron --model stabilityai/stable-diffusion-xl-base-1.0 --batch_size 1 --height 512 --width 512 --auto_cast matmul --auto_cast_type bf16 --num_images_per_prompt 1 ./sd_neuron/
```
The model gets deployed successfully but when the endpoint is invoked, the requests timeout.

```
aws-neuronx-runtime-discovery     2.9
libneuronxla                      2.0.4115.0
neuronx-cc                        2.15.128.0+56dc5a86
neuronx-distributed               0.9.0
optimum-neuron                    0.0.25
torch-neuronx                     2.1.2.2.3.0
transformers-neuronx              0.12.313
```

**Comment by philschmid** [comment]
Thank you can you share the logs from your endpoint? It could have multiple reasons why it timesout. Too long inference or different hyperparameters...

**Comment by pinak-p** [comment]
Closing the loop - this works with `inf2.8xlarge` but not with `inf2.xlarge`. Possibly a memory issue while loading the models.
