### ISSUE TITLE
instance type, typo and model reference

### ISSUE THREAD

**Issue by Zol-S** [philschmid/huggingface-inferentia2-samples#8]
1. Paragraph in the middle "After we have created the HuggingFaceModel we can deploy it to Amazon SageMaker using the deploy method. We will deploy the model with the ml.g5.48xlarge instance type." Previously you were writing about the deployment on ml.inf2.48xlarge, I think the ml.g5.48xlarge is just a mistake, right?
2. "This can takes a 20-30 minutes, we are working on improving the deployment time." take instead of takes
3. I set the "meta-llama/Llama-2-70b-chat-hf" for the HF_MODEL_ID variable as you did in the code, but shouldn't it be set to the compiled model for inferentia?

**Comment by philschmid** [comment]
Thank you for the typos. Fixed them in the blog. 

Regarding 3. that's described here: https://www.philschmid.de/inferentia2-llama-70b-inference#3-deploy-llama-2-70b-to-inferentia2. We pre-cached the compiled compilation that there is no need to compile it in advance.
